/**
 * Manifest — the compiler's only durable record of what has been built.
 *
 * There are deliberately no per-image metadata.json sidecars: the manifest
 * already holds everything, and duplicating it per directory would mean more
 * filesystem churn, more to clean up, and two things that can disagree.
 *
 * The consequence is that this file *is* the completion marker, so it is
 * flushed after every finished image rather than once at the end. A run killed
 * at image 167 of 218 leaves 166 recorded, and the next run skips them.
 */

import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';

/** Stable hash of the config that affects output bytes. Key order is sorted
 *  so a cosmetic reshuffle in config.mjs doesn't invalidate every asset. */
export function hashConfig(config) {
  const canonical = JSON.stringify(config, (_key, value) => {
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      return Object.fromEntries(Object.entries(value).sort(([a], [b]) => a.localeCompare(b)));
    }
    return value;
  });
  return crypto.createHash('sha256').update(canonical).digest('hex').slice(0, 16);
}

/** Read the previous manifest. A missing or unreadable file is a first run,
 *  not an error — the compiler simply rebuilds everything. */
export async function readManifest(manifestPath) {
  try {
    const parsed = JSON.parse(await fs.readFile(manifestPath, 'utf8'));
    return parsed?.images ?? {};
  } catch {
    return {};
  }
}

let nextFlushId = 0;

/**
 * Windows briefly reports EPERM/EBUSY on rename when a virus scanner or the
 * editor still holds the destination open. It clears in milliseconds, so a
 * short backoff is the difference between a spurious failed run and none.
 */
async function renameWithRetry(from, to, attempts = 5) {
  for (let i = 0; ; i++) {
    try {
      return await fs.rename(from, to);
    } catch (err) {
      const transient = err.code === 'EPERM' || err.code === 'EBUSY' || err.code === 'EACCES';
      if (!transient || i >= attempts - 1) throw err;
      await new Promise((r) => setTimeout(r, 20 * 2 ** i));
    }
  }
}

export function createManifestWriter({
  manifestPath,
  configHash,
  compilerVersion,
  baseUrl,
  sizes,
  formats,
}) {
  return {
    /**
     * Write the manifest atomically: a temp file in the same directory, then a
     * rename. A crash mid-write can therefore never leave a truncated JSON
     * file that would make the next run treat every image as new.
     */
    async flush(images) {
      const sorted = Object.fromEntries(
        Object.entries(images).sort(([a], [b]) => a.localeCompare(b))
      );
      const payload = {
        $comment:
          'Generated by `npm run publish-images`. Do not edit by hand — edit assets/originals/ and re-run.',
        compilerVersion,
        configHash,
        baseUrl,
        // Echoed so the frontend can resolve tiers without importing the
        // compiler config, which pulls node builtins into the browser bundle.
        sizes,
        formats,
        generatedAt: new Date().toISOString(),
        count: Object.keys(sorted).length,
        images: sorted,
      };

      await fs.mkdir(path.dirname(manifestPath), { recursive: true });
      // Unique per call, not just per process: the manifest is flushed once per
      // completed image, and two overlapping flushes sharing one temp path
      // would race (on Windows the second open handle makes the first rename
      // fail with EPERM).
      const tmp = `${manifestPath}.tmp-${process.pid}-${nextFlushId++}`;
      await fs.writeFile(tmp, `${JSON.stringify(payload, null, 2)}\n`, 'utf8');
      try {
        await renameWithRetry(tmp, manifestPath);
      } catch (err) {
        await fs.rm(tmp, { force: true }).catch(() => {});
        throw err;
      }
    },
  };
}

/** Stamp a freshly-built record with the provenance the scanner diffs against. */
export function stamp(record, { sourceHash, configHash, compilerVersion }) {
  return {
    ...record,
    sourceHash,
    configHash,
    compilerVersion,
    generatedAt: new Date().toISOString(),
  };
}
